Feature/ot111 23
alkemyTech/OT111-Server pull request #15
Opened 2021-11-30 19:57 UTC by MaximoDiNapoli

2021-12-01 04:36 UTC, OsvaldoGWP requested changes

2021-12-01 04:36 UTC, OsvaldoGWP commented on build.gradle
>  dependencies {
NOTA ANTES DE MERGEAR

Añadir el link de la tarea en la descripcion del pr
y en la tarea añadir el link del PR como un comentario
IMPORTANTE: actualizar con develop porq ya va haber conflictos cuando se empiece a aprobar los otros pr y a mergear

2021-12-01 04:36 UTC, OsvaldoGWP commented on build.gradle
> -	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
no borrar las dependencias que ya estan en develop, porq estan siendo usadas

2021-12-01 04:36 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/PostController.java
> +class TestCont {
Llamemos a la clase y archivo con la siguiente nomenclatura:

Si la entidad es Organization
Seria el controllador -> OrganizationController
y el servicio -> OrganizationService

2021-12-01 04:36 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/PostController.java
> +    @GetMapping(value = "/organization/public")
q la ruta sea /organization/{id}/public cosa de resivir el id como @PathVariable

2021-12-01 04:36 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/PostController.java
> +    public ResponseEntity test(@RequestBody String id) {
este metodo deberia devolver OrganizationDTO

2021-12-01 04:36 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/dto/OrganizationDTO.java
> +public class OrganizationDTO {
usar lombok para los getter setters

2021-12-01 04:36 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/service/PostManagmentService.java
> +public interface PostManagmentService {
Si te parece Maximo agendemos una reu para repasar como seria este servicio o sacar dudas

2021-12-03 00:27 UTC, MaximoDiNapoli commented on build.gradle
> -	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
la borre por que esta 2 veces

2021-12-04 23:16 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/PostController.java
> +        response.put("name",organization.getName());
retornar dto

2021-12-06 02:13 UTC, OsvaldoGWP requested changes

2021-12-06 02:13 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +
Falta la anotacion @Service para la injeccion de dependencia

2021-12-06 02:13 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +    public ResponseEntity test(@RequestBody Long id) {
- Response entity tiene q tener un tipo asio ResponseEntity<OrganizationDTO>
- la anotacion correcta es @PathVariable
- el nombre del metodo deberia ser algo como "getOrganization"

2021-12-06 02:13 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/dto/OrganizationDTO.java
> +    public static Map<String, String> smallOrganization(OrganizationEntity organization){
retornar el dto

2021-12-06 02:13 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +package com.alkemy.ong.controller;
probar el controlador y subir imagen del postman si es posible

2021-12-06 02:13 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +package com.alkemy.ong.controller;
he subido codigo a tu rama porfa chequearlo

2021-12-06 02:13 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +package com.alkemy.ong.controller;
queda pendiente lo de segurity consultar con equipo de seguridad

2021-12-07 13:34 UTC, closed without merging