Feature/ot111 29 dynamicTemplate
alkemyTech/OT111-Server pull request #24
Opened 2021-12-05 22:54 UTC by wallyjj277

se incorpora servicio de envio de email con template dinamico.

https://alkemy-labs.atlassian.net/browse/OT111-29

2021-12-06 01:48 UTC, OsvaldoGWP requested changes

2021-12-06 01:48 UTC, OsvaldoGWP commented on build.gradle
> +	implementation group: 'com.sendgrid', name: 'sendgrid-java', version: '4.8.1'
la dependencia ya esta declarada en la linea 28

2021-12-06 01:48 UTC, OsvaldoGWP commented on build.gradle
>  	implementation 'org.springframework.boot:spring-boot-starter-web'
IMPORTANTE:
- Actualizar con develop y resolver posibles conflictos

2021-12-06 01:48 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/service/sendgrid/EmailServiceImpl.java
> +    public String sendWithTemplate(String email, String user) {
el template deberia  recibirse en este metodo tambien

2021-12-06 16:13 UTC, wallyjj277 commented on build.gradle
> +	implementation group: 'com.sendgrid', name: 'sendgrid-java', version: '4.8.1'
ya quite la linea que sobra

2021-12-06 16:14 UTC, wallyjj277 commented on src/main/java/com/alkemy/ong/service/sendgrid/EmailServiceImpl.java
> +    public String sendWithTemplate(String email, String user) {
ya puse el envio de template por parametro

2021-12-06 16:16 UTC, wallyjj277 commented on build.gradle
>  	implementation 'org.springframework.boot:spring-boot-starter-web'
se actualizo con develop

2021-12-06 22:12 UTC, OsvaldoGWP requested changes

2021-12-06 22:12 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/UserEntity.java
> +
deberia descartar los cambios de este archivo, ya q no son correctos, quizas quedo de algun conflicto

2021-12-06 22:12 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/service/sendgrid/EmailServiceImpl.java
> +        mail1.setTemplateId(this.templateId);
el template q se pasa aqui deberia ser el q se recibe como parametro

2021-12-07 00:19 UTC, OsvaldoGWP requested changes

2021-12-07 00:19 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/UserEntity.java
> +
esta salto de linea no iria

2021-12-07 00:19 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/UserEntity.java
> +    private String photo;
desde aqui  hasta roleId no iria, borrar esas lineas

2021-12-07 00:19 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/UserEntity.java
> +
este salto de linea no iria tratemos de solo subir codigo y archivos necesarios y no comitear archivos q no corresponden quizas qdo de algun conflicto

2021-12-07 00:19 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/service/sendgrid/EmailServiceImpl.java
> +
falta setear el template Id

2021-12-07 01:57 UTC, wallyjj277 commented on src/main/java/com/alkemy/ong/service/sendgrid/EmailServiceImpl.java
> +
resuelto lo del template id lo volvi a poner

2021-12-08 18:23 UTC, OsvaldoGWP requested changes

2021-12-08 18:23 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/UserEntity.java
> +
no deberia eliminar este campo

2021-12-08 20:54 UTC, wallyjj277 commented on src/main/java/com/alkemy/ong/model/entity/UserEntity.java
> +
resuelto se agregaron los 2 campos que elimine

2021-12-08 21:05 UTC, OsvaldoGWP approved these changes

2021-12-08 21:06 UTC, OsvaldoGWP approved these changes

2021-12-08 21:06 UTC, merged