Feature/ot111 20
alkemyTech/OT111-Server pull request #28
Opened 2021-12-07 00:07 UTC by Juani-Ortizz

2021-12-07 00:10 UTC, Juani-Ortizz commented
https://alkemy-labs.atlassian.net/browse/OT111-20

Se crea modelo y repositorio de testimonials

2021-12-08 18:01 UTC, OsvaldoGWP requested changes

2021-12-08 18:01 UTC, OsvaldoGWP commented on build.gradle
>  	compileOnly 'org.projectlombok:lombok'
Actualizar con develop, falta repositorio

2021-12-08 18:01 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/Testimonial.java
> +@SQLDelete(sql = "UPDATE organization SET deleted = true WHERE id=?")
dice organization

2021-12-08 18:01 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/Testimonial.java
> +public class Testimonial {
estamos usando sufijo Entity, revisar las otras entities

2021-12-14 01:51 UTC, OsvaldoGWP approved these changes

2021-12-14 01:52 UTC, merged