Feature/ot111 72 Crear Seed Data de Usuarios
alkemyTech/OT111-Server pull request #32
Opened 2021-12-07 21:31 UTC by denisdimarco

https://alkemy-labs.atlassian.net/browse/OT111-72?atlOrigin=eyJpIjoiZGZkYmIyYzk1NDc4NGMzZGI5MzllNjU4MGFhNjJkN2MiLCJwIjoiaiJ9

Se consulto al equipo que formato de datos preferían para luego trabajar más cómodos.
Se creo el script users_seed.sql para poblar la base de datos con 10 administradores y 10 users regulares.
El script tiene 3 partes:

insertar el rol admin y rol user en la tabla roles
insertar 20 usuarios
asignar en la tabla user_role cada usuario a un rol admin o user.
Se agrego la info correspondiente al Readme.md

2021-12-08 18:51 UTC, OsvaldoGWP requested changes

2021-12-08 18:51 UTC, OsvaldoGWP commented on scripts/v0.1__users_seed.sql
> +INSERT INTO roles
detallito este insert para cargar roles ya esta en el script de role, me gusta q este en este script asi q lo eliminemos del escript de roles

2021-12-08 22:02 UTC, denisdimarco commented on scripts/v0.1__users_seed.sql
> +INSERT INTO roles
Eliminado el script de creacion de roles en role.sql

2021-12-09 22:09 UTC, OsvaldoGWP approved these changes

2021-12-09 22:09 UTC, merged