Feature/ot111 30
alkemyTech/OT111-Server pull request #34
Opened 2021-12-08 15:42 UTC by PadillaTom

### Summary
Intenté cambiar de nombre a la antigua rama (OT111-30) para meterla adentro de la carpeta "feature/OT111-30". Pero no me la cambió, sino que me creó una nueva rama.

2021-12-08 18:36 UTC, OsvaldoGWP requested changes

2021-12-08 18:36 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/auth/service/UserDetailsCustomService.java
> +        if(newUser != null) {
no va a ver un caso q esto sea null

2021-12-08 18:36 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/auth/service/UserDetailsCustomService.java
> +            // private String templateId = System.getenv("SENDGRID_TEMPLATE_ID");
templateId este valor lo pongamos en el application.yml, y lo consumamos desde aqui con @Value pero distingamos el nombre porq va a ver varios templates

2021-12-08 18:36 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/auth/service/UserDetailsCustomService.java
> +        //SendGrid Email:
Aqui tomas porfa t encargo compartir la apikey, en el canal de sengrid y el id del del template eso lo pongamos en el application.yml

2021-12-08 19:14 UTC, PadillaTom commented on src/main/java/com/alkemy/ong/auth/service/UserDetailsCustomService.java
> +            // private String templateId = System.getenv("SENDGRID_TEMPLATE_ID");
resuelto

2021-12-08 19:14 UTC, PadillaTom commented on src/main/java/com/alkemy/ong/auth/service/UserDetailsCustomService.java
> +        //SendGrid Email:
resuelto

2021-12-08 19:17 UTC, PadillaTom commented on src/main/java/com/alkemy/ong/auth/service/UserDetailsCustomService.java
> +        if(newUser != null) {
resuelto

2021-12-08 19:21 UTC, OsvaldoGWP commented on src/main/resources/application.yml
> +    tomas-template-id: d-a73c7ef24259456b91f84ffe1841d230
q se llame welcome-template

2021-12-09 09:02 UTC, PadillaTom commented
### Summary

- Por favor agregar ENV Variables.

**API_KEY puesta como String** 
![image](https://user-images.githubusercontent.com/59969816/145365427-0fa646c5-c17b-4ad9-8a3b-90ae274b5f20.png)

**SENDER puesto como String**
![image](https://user-images.githubusercontent.com/59969816/145365721-cfb8f367-0f2d-4c15-afdc-0af121505993.png)

### Evidence
- Arreglado Application.yml
![image](https://user-images.githubusercontent.com/59969816/145365805-373c4f4f-7734-4364-a37a-f5aa04c4a111.png)

- Envio correcto
![IMG_3142](https://user-images.githubusercontent.com/59969816/145365191-110c1e75-8db6-4e87-b4eb-6434f503fcce.PNG)

2021-12-09 15:42 UTC, PadillaTom commented
### Summary
Se agregan Variables de Entorno

### Evidence 
![image](https://user-images.githubusercontent.com/59969816/145427849-83b86eed-702c-4518-b04c-00d082577f71.png)

2021-12-09 22:41 UTC, OsvaldoGWP approved these changes

2021-12-09 22:41 UTC, merged