Feature/ot111 45
alkemyTech/OT111-Server pull request #39
Opened 2021-12-08 21:47 UTC by Crissil07

Tarea terminada - testeada con postman y funcionando - codigo a ver y corregir de ser necesario.

2021-12-10 21:52 UTC, OsvaldoGWP requested changes

2021-12-10 21:52 UTC, OsvaldoGWP commented on scripts/v0.1__news.sql
> +    "name"    VARCHAR(100)    NOT NULL,
Porfa agregar el link de la tarea y una descripcion sencilla para entender lo q se hizo

2021-12-10 21:52 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +        return ResponseEntity.status(HttpStatus.ACCEPTED).body(newsDTO);
Deberia retornar un status 200, revisar las convenciones de codigo de estados http

2021-12-10 21:52 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/response/category/CategoryDTO.java
> +    private boolean deleted = Boolean.FALSE;
para el dto de category sacarle los campos de auditoria y el deleted

2021-12-10 21:52 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/response/news/NewsDTO.java
> +    private CategoryEntity categoryId;
en un dto no deberia estar enlazado una entidad

2021-12-10 21:52 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/response/news/NewsDTO.java
> +    private OffsetDateTime createdDate;
sacar estos campos de auditoria

2021-12-10 21:52 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +        if (!toBeFound.isPresent()){
usar.isEmpty de opcional para no negar este if

2021-12-12 00:04 UTC, Crissil07 commented
COMO usuario administrador
QUIERO ver los detalles de una novedad
PARA poder informar actualizaciones del contenido

Criterios de aceptación:
GET a /news/:id . Mostrará todos los campos de una entry en base al id enviado por parámetro.

2021-12-12 15:17 UTC, OsvaldoGWP requested changes

2021-12-12 15:17 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/response/category/CategoryDTO.java
> +public class CategoryDTO {
ya existe el dto de category usar el q hicieron los compañeros

2021-12-12 15:17 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +        Optional <NewsEntity> toBeFound = newsRepository.findById(id);
Usar algo asi, ya q ahora se esta manejando las excepciones a nivel global ese throw q tira sino encuentra las news lo capturara nuestro manejador de errores (consultar a tomas sobre el controlAdvice)
`NewsEntity newsEntity = newsRepository.findById(id).orelsethrow();
        return newsMapper.entity2DTO(newsEntity );`

2021-12-12 15:19 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/response/news/NewsDTO.java
> +
Falta añadirle a q tipo de categoria pertenece esta noticia, recordar no usar la entity aca sino el dto de category

2021-12-12 17:06 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +        Optional <NewsEntity> toBeFound = newsRepository.findById(id);
PORFA chequear como quedo el crud de categoria y tomarlo como guia

2021-12-12 17:07 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/response/news/NewsDTO.java
> +
Actuallizar con develop y resolver conflictos

2021-12-14 03:11 UTC, OsvaldoGWP approved these changes

2021-12-14 03:11 UTC, merged