Feature/ot111 38 - Crear cliente AmazonS3 | Subir imagen con Role_ADMIN
alkemyTech/OT111-Server pull request #43
Opened 2021-12-09 14:25 UTC by kida10-tech

- Se agregan las Propiedades de Amazon Web Service al application.yml
- Se crea un Cliente AmazonS3 para asignar las credenciales de AWS.
- Se crea un controller con un metodo POST para la carga de la imagen.
- En las configuraciones de seguridad se agrega un antMatchers con la ruta y el acceso único a ADMIN.
- Se prueba en Postman de manera OK cuando se loguea como ADMIN y un 403 al loguearse como USER.

2021-12-12 17:10 UTC, OsvaldoGWP requested changes

2021-12-12 17:10 UTC, OsvaldoGWP commented on src/main/resources/application.yml
>      jpa:
chequear q abajo se estan subiendo archivos q no deberian los .class y uno q dice application.properties

2021-12-12 17:10 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/service/impl/AWSServiceImpl.java
> +public class AWSServiceImpl implements AWSService {
Se ve todo ok, porfa actualizar con develop, resolver conflictos para poder mergear

2021-12-13 00:33 UTC, kida10-tech commented on src/main/resources/application.yml
>      jpa:
Ya elimine esas clases target, por error!

2021-12-13 18:37 UTC, OsvaldoGWP approved these changes

2021-12-13 18:37 UTC, merged