Feature/ot111 57 endpoint creacion slides
alkemyTech/OT111-Server pull request #59
Opened 2021-12-15 01:36 UTC by wallyjj277

creado el endpoint de creacion de slides, con el servicio y el controller, se hicieron algunos fixes al script y a entity slides
enlace de jira: https://alkemy-labs.atlassian.net/browse/OT111-57
evidence:
![slide creada en dbeaver](https://user-images.githubusercontent.com/89556738/146106494-994f82b5-4b72-4c21-9c47-6ad6ca4a2613.png)
![crear slides funciona postman](https://user-images.githubusercontent.com/89556738/146106501-28cf8e3f-520f-4589-93d9-1f1de9568639.png)

2021-12-15 04:09 UTC, OsvaldoGWP requested changes

2021-12-15 04:09 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/SlideEntity.java
> +    private OffsetDateTime created_date = OffsetDateTime.now();
los nombres de los campos de auditoria estan con _ en este archivo  normalizar como lo tenemos en las demas entities

2021-12-15 04:09 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/mapper/SlideMapper.java
> +    public SlideResponseDTO buildToList(SlideEntity entity) {
este no se esta usando por el momento asi q lo saquemos y agregar cuando haga falta si es q hace falta

2021-12-15 04:09 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/request/SlideRequestDTO.java
> +    private OrganizationEntity organization;
desde el front deberiamos mandar solo el id de la organizacion

2021-12-15 04:09 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/response/SlideResponseDTO.java
> +    private OrganizationEntity organization;
en el response recordar de usar dto si tiene relaciones osea aqui deberia usar el dto de organizacion

2021-12-15 04:09 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +
Estuve leyendo la tarea  dice q se tiene q hay q mandar una imagen y guardar esa imagen en el s3, porfa chequear eso, lo de imagen lo estuvieron trabajando diego y tomas
NOTA de lo q dice la tarea:
Recibirá la imágen a almacenar en base 64. La misma deberá ser decodeada y almacenada en Amazon S3.

2021-12-15 22:31 UTC, wallyjj277 commented on src/main/java/com/alkemy/ong/model/entity/SlideEntity.java
> +    private OffsetDateTime created_date = OffsetDateTime.now();
resuelto se cambio

2021-12-15 22:32 UTC, wallyjj277 commented on src/main/java/com/alkemy/ong/model/mapper/SlideMapper.java
> +    public SlideResponseDTO buildToList(SlideEntity entity) {
resuelto se elimino se pondra si es requerido en un futuro

2021-12-15 22:32 UTC, wallyjj277 commented on src/main/java/com/alkemy/ong/model/request/SlideRequestDTO.java
> +    private OrganizationEntity organization;
se cambio por el id de organization

2021-12-15 22:32 UTC, wallyjj277 commented on src/main/java/com/alkemy/ong/model/response/SlideResponseDTO.java
> +    private OrganizationEntity organization;
se cambio el entity por el dto

2021-12-16 22:04 UTC, OsvaldoGWP requested changes

2021-12-16 22:04 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/request/SlideRequestDTO.java
> +    private long organization_id;
aqui respetar la nomenclatura de nombres para la variables seria organizationId tipo Long y agregarle el @NotNull

2021-12-16 22:05 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/request/SlideRequestDTO.java
> +    private long organization_id;
despues todo el resto se ve muy bien lo q si falta lo de guardar la imagen del s3 me avisas luego como va eso @wallyjj277 @PadillaTom

2021-12-19 03:12 UTC, OsvaldoGWP approved these changes

2021-12-19 03:14 UTC, merged