Feature/ot111 47 - PUT - Endpoint Actualización Novedades por id
alkemyTech/OT111-Server pull request #61
Opened 2021-12-16 21:14 UTC by Crissil07

2021-12-16 21:28 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
> +                .antMatchers("/test/user-admin").hasAnyRole("ADMIN", "USER")
Ojo que aca estas agregando .antMatchers que ya se han sacado de develop. Quizás no actualizaste antes de hacer el PR.

2021-12-16 21:28 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +    })
La documentación es de la tarea OT111-86

2021-12-16 21:42 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +    })
No estaria faltando @Operation(summary = "Actualizar novedad") que va abajo del @PutMapping 
Estaria bueno que en vez de "Noticia actualizada" fuera "Novedad actualizada" siguiendo la nomenclatura de la tarea.

2021-12-16 22:07 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +    })
gracias denis no vi ese detalle del @Operation 👍

2021-12-16 22:11 UTC, OsvaldoGWP requested changes

2021-12-16 22:11 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +        foundNews.setId(newsDTO.getId());
el id no se deberia pisar

2021-12-16 22:28 UTC, Crissil07 commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +        foundNews.setId(newsDTO.getId());
Resuelto

2021-12-16 22:29 UTC, Crissil07 commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +    })
Resuelto

2021-12-17 19:20 UTC, OsvaldoGWP approved these changes

2021-12-17 19:20 UTC, merged