Feature/ot111 56 detalle slides
alkemyTech/OT111-Server pull request #68
Opened 2021-12-19 07:10 UTC by wallyjj277

- se crea el enpoint de detalle de slides
- se agregan los metodos en la clase Service y ServiceImpl
- se agregan anotaciones de Swagger
- se le da acceso en la clase de autorizacion 
Se adjunta evidencia:
si no lo encuentra tira 404
![detalle slide 404](https://user-images.githubusercontent.com/89556738/146666920-5d65a305-bf36-41fc-a10b-7945fae33cd1.png)
la que esta guardada en la base de datos
![detalle slide db](https://user-images.githubusercontent.com/89556738/146666921-38f0d211-1aa1-4528-a538-6ceb10b56eed.png)
si la encuentra devuelve 200
![detalle slide ok](https://user-images.githubusercontent.com/89556738/146666922-7e85cd70-9941-4094-91ee-2972707e6ef3.png)

adjunto link de la tarea:
https://alkemy-labs.atlassian.net/browse/OT111-56

2021-12-19 16:10 UTC, denisdimarco requested changes
Yo lo probe y me funciona bien también! Hay que revisar el tema de:

- Usar un solo tipo de inyección de dependencias.
-  Hay varios /TODOs abiertos
-  En el SlideMapper pondríamos inyectar el Mapper de Organization, pero igual funciona.
-

2021-12-19 16:10 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +    })
Se podría mejorar el tema de las mayusculas al inicio de cada oración en summary y description.
En el @ApiResponse(responseCode = "404) podríamos agregar la clase que tira el error algo así : 

```java
 @ApiResponse(
                            responseCode = "404",
                            description = "Slide no encontrado.",
                            content = {
                                    @Content(mediaType = "application/json",
                                            schema = @Schema(implementation = ApiException.class))

                            }
                    )
```

2021-12-20 00:00 UTC, wallyjj277 commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +    })
resuelto lo de las mayusculas, lo de la mejora del codigo de respuesta, el /TODO de la inyeccion de las dependencias lo iba a arreglar cuando tuviese toda la clase slides mergeada con todos los metodos para no ir tocando una por una. lo del mapper no sabria decirte como hacer pero si funcia no lo tocaria

2021-12-20 14:47 UTC, OsvaldoGWP approved these changes

2021-12-20 14:48 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +    })
En las anotaciones del swagger de @ApiResponse que devuelven error se puede agregar el  schema = @Schema(implementation = ApiException.class) para que el swagger muestre el modelo de respuesta de error.
Te queda asi por ejemplo: 
![image](https://user-images.githubusercontent.com/87948501/146785790-b4a1bd53-2956-4dc4-85b2-21428a8d7a93.png)

2021-12-20 14:49 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +    })
Buenas observacione denis @denisdimarco , yo agregue esos todos para q los revise alejandro, porfa alejandro  @wallyjj277 cuando creas conveniente los solucionas mientras antes mejor 👍

2021-12-20 14:51 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +    })
Con respecto a lo del mapper de organizacion, deberias usarlo sino no estas reutilazando el codigo ya creado, si bien anda lo correcto es reutilizar el mapper de organizacion en el mapper de slide

2021-12-20 14:51 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +    })
mientras voy mergeando este codigo 👍

2021-12-20 14:52 UTC, merged