Feature/ot111 18
alkemyTech/OT111-Server pull request #7
Opened 2021-11-28 04:04 UTC by denisdimarco

[https://alkemy-labs.atlassian.net/browse/OT111-18](https://alkemy-labs.atlassian.net/browse/OT111-18)

- Created Category Entity
- Created Category Script
- Created Category Repository

- Added Gradle dependencies and updated application.yml.

2021-11-29 18:01 UTC, OsvaldoGWP requested changes

2021-11-29 18:01 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/CategoryEntity.java
> +    @NotNull
este notnull no aplica para tipos de datos primitivos

2021-11-29 18:01 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/CategoryEntity.java
> +    @NotNull
para los string podemos usar @NotEmpty ya q aparte de controllar q no sea nulo tambien controla q no sea puro espacios en blancos

2021-11-29 18:01 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/CategoryEntity.java
> +    private OffsetDateTime createdDate;
este campo lo inicialicemos por defecto

2021-11-29 18:01 UTC, OsvaldoGWP commented on build.gradle
>  	implementation 'org.springframework.boot:spring-boot-starter'
IMPORTANTE: actualizar con develop porq ya va haber conflictos cuando se empiece a aprobar los otros pr y a mergear

2021-11-29 18:03 UTC, OsvaldoGWP commented on build.gradle
> +	testImplementation 'org.springframework.boot:spring-boot-starter-test'
dependencia repetida

2021-11-29 21:54 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/model/entity/CategoryEntity.java
> +    @NotNull
- [x] @NotNull deleted

2021-11-29 22:03 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/model/entity/CategoryEntity.java
> +    @NotNull
- [x] Changed `@NotNull -->  @NotEmpty` in String fields

2021-11-29 22:04 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/model/entity/CategoryEntity.java
> +    private OffsetDateTime createdDate;
- [x] Removed @NotNull

2021-11-29 22:08 UTC, denisdimarco commented on build.gradle
> +	testImplementation 'org.springframework.boot:spring-boot-starter-test'
Removed duplicated dependency.

2021-12-01 01:14 UTC, OsvaldoGWP approved these changes

2021-12-01 01:14 UTC, merged