Feature/ot111 103 - Modulo Organization
alkemyTech/OT111-Server pull request #87
Opened 2021-12-23 15:53 UTC by denisdimarco

#### Abarca las tareas de JIRA: 
https://alkemy-labs.atlassian.net/browse/OT111-37
https://alkemy-labs.atlassian.net/browse/OT111-63
https://alkemy-labs.atlassian.net/browse/OT111-64
https://alkemy-labs.atlassian.net/browse/OT111-92
https://alkemy-labs.atlassian.net/browse/OT111-103

#### Resumen: 
**En rama OT111-37:**
- Se actualizo OrganizationEntity y Organization.sql para agregar redes sociales.
- OrganizationEntity extiende de Auditable Entity ahora.
- Se actualization las configuraciones de seguridad y se agregó constante para el path.
- Se agrego handleMethodArgumentNotValid al ApiExceptionHandler.
- Se Modifico los DTOs de organización a formato Request y Response.
- Se refactoreo endpoint GET /organization/public endpoint acorde a lo que pide la tarea original.
- Se creo el endpoint PUT /organization/public
- Se agregaron a controller el POST y DELETE a fines de practica. (no eran pedidos por las tareas)
- Renamed mappers.

**Se mergeo la branch OT111-37 a la OT111-103:** :
- Refactoreados paths de los endpoints en OrganizationController
- Se agregaron 17 test, los cuales pasaron el 100% coverage de OrganizationController.
- Revisado con Sonar.

#### Evidencia de testing:

<img width="1543" alt="image" src="https://user-images.githubusercontent.com/87948501/147263637-292f37db-6e01-4b0b-96d1-7af1f55adcdf.png">

<img width="903" alt="image" src="https://user-images.githubusercontent.com/87948501/147263741-40709839-7509-4922-a2c1-389760204c1c.png">

<img width="936" alt="image" src="https://user-images.githubusercontent.com/87948501/147263825-117a6ae9-3d06-426a-8869-6397d52107f3.png">

2021-12-23 17:47 UTC, OsvaldoGWP requested changes

2021-12-23 17:47 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/response/OrganizationFullResponse.java
> +    public static OrganizationEntity refreshData(OrganizationEntity organizationEntity, OrganizationRequest organizationRequest) {
Lo corrcto seria q el toEntity y el refreshData esten en el request, ya q no es una responsabilidad del response

2021-12-23 17:47 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        return OrganizationFullResponse.toDTO(organizationRepository.save(OrganizationFullResponse.toEntity(request)));
cuando muevas la logica para hacer el toEntity al request t deberia qdar algo asi

return OrganizationFullResponse.toDTO(organizationRepository.save(request.toEntity());

2021-12-23 17:47 UTC, OsvaldoGWP commented on src/test/java/com/alkemy/ong/controller/OrganizationControllerTest.java
> +    void getOrganizationPublic_Expected_NotFound() throws Exception {
este test podria fallar en el hipotetico caso de que:

en la base ya haya varias organizaciones creadas, por ende solo elimine la ultima, y el get me va a traer la anterior y no va a pasar el test, por el momento diria de sacar este test

2021-12-23 17:47 UTC, OsvaldoGWP commented on src/test/java/com/alkemy/ong/controller/OrganizationControllerTest.java
> +    void createOrganization_expectBadRequest_invalidName() throws Exception {
aqui para los badRequest englobaria todos los posibles campos invalidos y solo tener un solo test para controlar esos campos invalidos y en poner result.andExpect(jsonPath("$.errors.length()").value(xxxx));

Nota: los test de integracion son costosos, osea en tiempo de ejecucion hay una piramide de test en la cual explica q cantidad de test es recomendable para cada caso

dejo un link de muchos 
https://cl.abstracta.us/blog/piramide-de-automatizacion/

2021-12-23 17:47 UTC, OsvaldoGWP commented on src/test/java/com/alkemy/ong/controller/OrganizationControllerTest.java
> +    @WithMockUser(username = "userMock", roles = "ADMIN")
aqui mismo enfoque que arriba no tener un test para actualizar cada campo, quizas solo 2 uno donde mandas a actualizar algunos campos y otro donde actualizas todo

2021-12-24 02:23 UTC, denisdimarco commented on src/test/java/com/alkemy/ong/controller/OrganizationControllerTest.java
> +    void getOrganizationPublic_Expected_NotFound() throws Exception {
Test omitido

2021-12-24 02:28 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        return OrganizationFullResponse.toDTO(organizationRepository.save(OrganizationFullResponse.toEntity(request)));
Refactoreado, lo unico que deje el toEntity con el builder.

2021-12-24 03:04 UTC, denisdimarco commented on src/test/java/com/alkemy/ong/controller/OrganizationControllerTest.java
> +    void createOrganization_expectBadRequest_invalidName() throws Exception {
Excelente la data! Gracias!

2021-12-24 03:05 UTC, denisdimarco commented on src/test/java/com/alkemy/ong/controller/OrganizationControllerTest.java
> +    @WithMockUser(username = "userMock", roles = "ADMIN")
Resuelto.

2021-12-24 03:08 UTC, denisdimarco commented
Evidencia de tests:

<img width="999" alt="image" src="https://user-images.githubusercontent.com/87948501/147311173-a5f912dd-8df0-4bcc-a2e4-001a273e267a.png">

2021-12-24 17:32 UTC, OsvaldoGWP approved these changes

2021-12-24 17:32 UTC, merged