Feature/ot111 19
alkemyTech/OT111-Server pull request #9
Opened 2021-11-28 06:19 UTC by denisdimarco

[https://alkemy-labs.atlassian.net/browse/OT111-19](https://alkemy-labs.atlassian.net/browse/OT111-19)

- Created News Entity

- Created News Script

- Created News Repository

Added Gradle dependencies and updated application.yml.

2021-11-29 18:13 UTC, OsvaldoGWP requested changes

2021-11-29 18:13 UTC, OsvaldoGWP commented on build.gradle
> +	testImplementation 'org.springframework.boot:spring-boot-starter-test'
dependencia repetida

2021-11-29 18:13 UTC, OsvaldoGWP commented on scripts/v0.1__news.sql
> +    category_id int8 NOT NULL, --CONFIRM NOT NULL
correcto esto va a ser not null

2021-11-29 18:13 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/NewsEntity.java
> +@Table(name = "news") //Both singular and plural of "news" word it's the same.
gracias por el comentario

2021-11-29 18:13 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/NewsEntity.java
> +    @NotNull //Confirm annotation
Usar alco como esto
 @ManyToOne(fetch = FetchType.LAZY)
 @JoinColumn(name = "employee_id")
 
 dejo link: https://www.baeldung.com/jpa-join-column
 
 y dejo wiki: https://github.com/alkemyTech/OT111-Server/wiki/Capa-Repository-(JPA,-Entity,-etc)

2021-11-29 18:13 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/NewsEntity.java
> +    private OffsetDateTime createdDate;
este campo inicializarlo por defecto y ya no haria falta el notnull

2021-11-29 18:13 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/NewsEntity.java
> +    private boolean deleted = Boolean.FALSE;
@notNull no aplica para tipos primitivos

2021-11-29 22:37 UTC, denisdimarco commented on build.gradle
> +	testImplementation 'org.springframework.boot:spring-boot-starter-test'
Removed duplicated dependency.

2021-11-30 00:05 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/model/entity/NewsEntity.java
> +    @NotNull //Confirm annotation
Agregue las anotaciones a categoryId, pero me queda la duda si esto hace que agregar una anotacion @OneToMany(mappedBy="category") y agregar una Lista de news en CategoryEntity aunque no se pida en los requisitos de esa entidad.

```Java
@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    //TODO missing CategoryEntity from feature/OT111-18
    //TODO ask if need in CategoryEntity: @OneToMany(mappedBy="category")
    private CategoryEntity categoryId;
```

2021-12-01 03:51 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/entity/NewsEntity.java
> +    @NotNull //Confirm annotation
No haria falta añadir la lista de noticias en categoria ya que solamente nos interesa solo este lado de la relacion y no de ambos sentidos (hay caso q si se lo requiere), nose si me explico y sino lo vemos nuevamente

2021-12-01 03:51 UTC, OsvaldoGWP approved these changes

2021-12-01 03:52 UTC, merged