OT111-66 Endpoint Actualización Testimonios
alkemyTech/OT111-Server pull request #90
Opened 2021-12-24 21:08 UTC by MaximoDiNapoli

https://alkemy-labs.atlassian.net/browse/OT111-66?atlOrigin=eyJpIjoiM2JhMzU2YjkxNjlhNGY1Njk2NmYyODMyY2NiMWQ5NDQiLCJwIjoiaiJ9

Endpoint Actualización Testimonios

2021-12-26 23:01 UTC, denisdimarco requested changes

2021-12-26 23:01 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +@RequestMapping("testimonials")
Podes agregar `@Tag(name = "Testimonios")` para la documentacion de Swagger.

2021-12-26 23:01 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +    })
El @ApiResponses y los @ApiResponse no son necesario ya que Swagger maneja automaticamente los Schemas y los codigos de respuesta de error.

2021-12-26 23:01 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +        return ResponseEntity.ok(testimonialService.updateTestimonial(TestimonialRequestDTO, id));
Si agregas el @Valid te valida los `@NotEmpty` del DTO automaticamente:
```java
@Valid @RequestBody TestimonialRequestDTO
```

2021-12-26 23:01 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/model/dto/TestimonialDTO.java
> +}
Esta clase no seria necesaria ahora, ya que la estas usando solamente para el Schema de la @ApiResponse y eso hay que sacarlo. Asi que podes eliminarla.

2021-12-26 23:01 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/model/entity/TestimonialEntity.java
Podes extender TestimonalEntity de AuditableEntity:

```java
public class TestimonialEntity extends AuditableEntity {
```
Esta clase incluye todo este codigo que repetimos en todas las entidades, asi podes eliminarlo de TestimonialEntity: 
```java
    private OffsetDateTime createdDate;
    private String createdBy;
    private OffsetDateTime modifiedDate;
    private String modifiedBy;
    private boolean deleted = Boolean.FALSE;
```
Y de paso te metodos necesario para los test!

2021-12-26 23:01 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/model/mapper/TestimonialMapper.java
> +    public TestimonialResponseDTO entity2DTO(TestimonialEntity ent) {
Si te sobra tiempo se puede simplificar el nombre de los metodos entity2DTO a **toDTO** y dto2Entity a **toEntity**

2021-12-26 23:01 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/repository/TestimonialRepositoty.java
> +public interface TestimonialRepositoty extends JpaRepository<TestimonialEntity, Long>{
Si hay tiempo se podria renombrar el nombre de la clase a TestimonialRepository

2021-12-26 23:02 UTC, denisdimarco commented
Tambien podes dejar evidencia de funcionamiento poniendo capturas de las pruebas que hagas con postman.

2021-12-27 17:17 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/repository/TestimonialRepositoty.java
> +public interface TestimonialRepositoty extends JpaRepository<TestimonialEntity, Long>{
muy bien esto no lo vi 👀

2021-12-27 17:18 UTC, OsvaldoGWP requested changes

2021-12-27 17:18 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +    public ResponseEntity<TestimonialResponseDTO> updateTestimonial(@RequestBody TestimonialRequestDTO TestimonialRequestDTO, @PathVariable Long id) {
la variable TestimonialRequestDTO deberia empezar con minuscula

2021-12-27 19:27 UTC, MaximoDiNapoli commented
> Tambien podes dejar evidencia de funcionamiento poniendo capturas de las pruebas que hagas con postman.
La mande al server de disc pero la dejo aca tambien 
![imagen](https://user-images.githubusercontent.com/63366993/147501459-bf11727a-740d-4593-a597-cd4683dcecbd.png)

2021-12-27 22:00 UTC, closed without merging