feature/OT111-90 - UserController Tested OK
alkemyTech/OT111-Server pull request #92
Opened 2021-12-24 23:23 UTC by kida10-tech

- Se testean todos los endpoints de UserController de manera satisfactoria.
- Se realizan pruebas de éxito y error.
- Se evidencian dichas pruebas.

Captura de Pantalla 2021-12-24 a la(s) 19 56 21

Captura de Pantalla 2021-12-24 a la(s) 19 55 02

Captura de Pantalla 2021-12-24 a la(s) 19 54 19

Captura de Pantalla 2021-12-24 a la(s) 19 52 57

Captura de Pantalla 2021-12-24 a la(s) 19 52 10

Captura de Pantalla 2021-12-24 a la(s) 19 51 33

Captura de Pantalla 2021-12-24 a la(s) 19 50 46

Captura de Pantalla 2021-12-24 a la(s) 19 49 27

2021-12-27 15:09 UTC, OsvaldoGWP requested changes

2021-12-27 15:09 UTC, OsvaldoGWP commented on src/test/java/com/alkemy/ong/controller/UserControllerTest.java
> +    void deleteUser_fail() throws Exception {
este test va a fallar, la idea es q todos los test q se corran pasen, si quieres testear un caso fallido deberia controllar en el mismo test q espera q falle, nose si me explico sino lo vemos

2021-12-28 00:41 UTC, kida10-tech commented on src/test/java/com/alkemy/ong/controller/UserControllerTest.java
> +    void deleteUser_fail() throws Exception {
Ya estuvo corregido. Gracias

2021-12-28 01:04 UTC, OsvaldoGWP approved these changes

2021-12-28 01:04 UTC, merged