Feature/ot111 65
alkemyTech/OT111-Server pull request #93
Opened 2021-12-26 19:07 UTC by Juani-Ortizz

Falta agregar endpoint return

2021-12-26 19:08 UTC, Juani-Ortizz commented
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT111/boards/168?modal=detail&selectedIssue=OT111-65

2021-12-27 17:21 UTC, OsvaldoGWP requested changes

2021-12-27 17:21 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +    public String saveTestimonial(@Valid @ModelAttribute TestimonialEntity testimonialEntity, BindingResult result, Model model){
👀  chequear como estan los otros endpoint de guardado
Lo de  @ModelAttribute es de spring framework se mas para mvc aqui no aplica

2021-12-27 17:21 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +        System.out.println("Testimonial saved");
System.out.println("Testimonial saved"); no deberiamos llevar estas lineas a codigo de produccion

2021-12-27 17:21 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +        System.out.println("Testimonial saved");
usar Log.... usar @SLF4 de lombok

2021-12-27 23:45 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +        System.out.println("Testimonial saved");
@PadillaTom

2021-12-28 00:59 UTC, PadillaTom commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +    public String saveTestimonial(@Valid @ModelAttribute TestimonialEntity testimonialEntity, BindingResult result, Model model){
Resuelto

2021-12-28 00:59 UTC, PadillaTom commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +        System.out.println("Testimonial saved");
Resuelto

2021-12-28 01:16 UTC, OsvaldoGWP approved these changes

2021-12-28 01:16 UTC, merged