Feature/ot111 104 Modulo Users
alkemyTech/OT111-Server pull request #94
Opened 2021-12-27 02:10 UTC by danit3x

Se modifico userDTO y requestUserDTO por UserResponse y UserRequest.
se implemento ResponseStatus, Valid, UserEntity extends AuditableEntity,
en Response y request se coloco metodos toDTO y toEntity.
reemplaza Autowired por RequiredsArgsconstructor.

------ Admin -----
Delete
<img width="950" alt="AdminDeleteOk" src="https://user-images.githubusercontent.com/64555508/147427223-9cc1a214-84d8-444d-8457-73643fd6408c.PNG">
FindbyId
<img width="950" alt="AdminFindByIdOk" src="https://user-images.githubusercontent.com/64555508/147427224-d70fe20e-5e4e-476c-870a-b60f7ff6f519.PNG">
GetAllUsers
<img width="950" alt="AdminGetAllUserOk" src="https://user-images.githubusercontent.com/64555508/147427227-6c2cb6af-1d99-462e-8716-3f5fb02dbc79.PNG">
Update
<img width="950" alt="AdminUpdateByIdOk" src="https://user-images.githubusercontent.com/64555508/147427230-e8588e68-58b5-41f6-81ac-cb2e4a362817.PNG">

----- Not Logged Forbidden ----
<img width="950" alt="NotLoggedForbidden" src="https://user-images.githubusercontent.com/64555508/147427232-23879ca2-2ae1-46f6-acef-bbca52894c51.PNG">

.---- User Forbidden -----
<img width="950" alt="UserForbidden" src="https://user-images.githubusercontent.com/64555508/147427235-ace62d41-6488-4dca-b445-4b814d19591f.PNG">

2021-12-27 15:20 UTC, OsvaldoGWP requested changes
dewspues el resto se ve bien 👍

2021-12-27 15:20 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/request/UserRequest.java
> +    public static UserEntity updateEntity(UserRequest request, UserEntity foundUser,List<RoleEntity> role) {
el nombre de la variable role lo correcto seria roles q ya es una lista

2021-12-27 15:20 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/request/UserRequest.java
> +    private static RoleRepository roleRepository;
esto no deberia ir aqui y ademas no se esta usando

2021-12-27 15:20 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/model/response/UserResponse.java
> +public class UserResponse extends AuditableEntity {
AuditableEntity se creo sola para usarse a nivel de entidades, ya que tiene anotaciones especificas de jpa

2021-12-27 15:20 UTC, OsvaldoGWP commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> +    public UserServiceImpl(UserRepository userRepository, PasswordEncoder passwordEncoder, RoleRepository roleRepository) {
Si esta usando @RequiredArgConstructor no deberia declarar nuevamente un constructor ya q la anotacion lo esta haciendo

2021-12-27 15:46 UTC, denisdimarco requested changes

2021-12-27 15:46 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/model/request/UserRequest.java
> +public class UserRequest extends AuditableEntity {
Me parece que UserRequest no debería extender de AuditableEntity.

2021-12-27 15:46 UTC, denisdimarco commented on src/main/java/com/alkemy/ong/model/response/UserResponse.java
> +public class UserResponse extends AuditableEntity {
Mismo caso que con Request, UserResponse no debería extender de AuditableEntity. Solo las entidades extienden de AuditableEntity, si no te agrega y solicita datos que no corresponden en las Request y Response.

2021-12-28 00:46 UTC, OsvaldoGWP approved these changes

2021-12-28 00:46 UTC, merged